### ISSUE TITLE
Package 'request' is using a buggy transitive dependency

### ISSUE THREAD

**Issue by aschrijver** [datproject/dat#850] opened 2017-08-16 10:15 UTC
This issue is just to notify you that `request` depends on `aws-sign2` v0.6.0 which has a bug in it: a duplicate export. This has been fixed in 0.7.0 but the wait is for a new release of `request`.
Probably this does not lead to issues with `dat`, I expect.

I created an issue, asking for a date:
- https://github.com/request/request/issues/2742

(found this while testing `rollup` with `dat` project: https://github.com/request/request/issues/2483)

**Comment by ralphtheninja** [comment] 2017-08-16 10:50
Maybe we can swap out request to something else?

**Comment by aschrijver** [comment] 2017-08-16 11:18
@ralphtheninja Maybe its not that much of an issue. I have excluded it in the bundle.js and think its only for people wanting to connect to AWS or something. The bundling with rollup now works (it bundles, don't know if it executes yet :)

**Comment by okdistribute** [comment] 2020-03-27 02:48
duplicate of #1176

**Closed by okdistribute** 2020-03-27 02:48 UTC
Labels: Type: Maintenance
