### ISSUE TITLE
Duplicate entries written to the hyperdrive

### ISSUE THREAD

**Issue by pfrazee** [datproject/dat#542] opened 2016-10-10 14:42 UTC
As described in https://github.com/datproject/dat/issues/540, there are times when dat adds duplicate entries for new files. Gremlins?

**Comment by joehand** [comment] 2016-10-10 15:00
Thanks. Probably related to: [hyperdrive-import-files #20](https://github.com/juliangruber/hyperdrive-import-files/issues/20)

**Comment by juliangruber** [comment] 2016-10-10 16:18
fixed in https://github.com/juliangruber/hyperdrive-import-files/pull/21

**Comment by pfrazee** [comment] 2016-10-10 16:36
I'll need to test to be sure. I was seeing duplicate file entries, not duplicate folders.

**Comment by karissa** [comment] 2016-10-10 16:43
duplicate files come from the `list` command being incorrect.

**Comment by joehand** [comment] 2016-10-10 16:52
@karissa the duplicate list items is one issue (which is mostly solved if we use hyperdrive-stats or when @pfrazee's hyper PR lands).

There is another issue with files getting _added_ twice to metadata when they shouldn't (e.g. `mtime`, `size`, and all other metadata the exact same). I think this was the issue TheLink saw in #539 too.

**Comment by pfrazee** [comment] 2016-10-10 16:54
@joehand yeah, and I agree that 539 looks like the same issue

**Comment by juliangruber** [comment] 2016-10-10 16:59
ah, the issue potentially is that with `{ resume: false }` hyperdrive-import-files doesn't compare anything before overwriting file entries. I guess we can change dat to use `{ resume: true }` all the time.

**Comment by joehand** [comment] 2016-10-10 22:23
> ah, the issue potentially is that with { resume: false } hyperdrive-import-files doesn't compare anything before overwriting file entries. I guess we can change dat to use { resume: true } all the time.

Oh wow, exactly! Great finding that @juliangruber. 

I talked to @mafintosh a bit about the watching (related to EMFILE error, #524). We are thinking we may want to batch check for changes rather than watch all files live. 

The other option would be to do the initial import, set resume: true, then start watching files. Right now files are watched before they are imported which may lead to some other double import edge cases.

**Comment by joehand** [comment] 2016-10-10 22:42
> Oh wow, exactly! Great finding that @juliangruber.

Well, maybe not exactly. The resume shouldn't matter once the live is going. The watcher is firing when it shouldn't (the file isn't modified but a change event is happening). But it seems like we should also [guard from this in hyperdrive](https://github.com/mafintosh/hyperdrive/issues/107) (the exact same entry+ metadata).

**Comment by juliangruber** [comment] 2016-10-11 15:32
Super tough spot here. Hashing is the only reliable way to solve this, as {m,c}times _can_ be off. However, most of the time, they _aren't_.

Overall I expect our stack to be simple with hashing though.

**Comment by pfrazee** [comment] 2016-10-11 15:35
> as {m,c}times can be off

What are the specific cases you're thinking of? If it's just, the mtime/ctime changed without the *content* changing, I don't think I'd want a new entry written.

But if there are cases where we do want to write if mtime/ctime changes, or some other attribute, we can actually do a comparison by multiple attributes. Eg: write if hash is different, OR mtime is different, OR ctime is different, etc.

**Comment by juliangruber** [comment] 2016-10-11 15:42
@pfrazee your computer's local time can simply be off. Some tool can manually set an mtime to a wrong time, which happened to me before. In contrast, hashing a file is 100% reliable.

**Comment by pfrazee** [comment] 2016-10-11 16:16
@juliangruber yeah but this isnt a distributed system, "our clocks arent uniform" problem. This is a local, "are we correctly detecting changes" issue. Even if the local clock was wonky, AFAIK that *shouldnt* be causing the files' mtimes/ctimes to change without new writes occurring

**Comment by juliangruber** [comment] 2016-10-11 16:20
| your clock might have been off for some time, e.g. while you were changing time zones.

from https://github.com/juliangruber/backer/issues/9 where we had this discussion before

**Comment by pfrazee** [comment] 2016-10-11 16:41
I see, so it can lead to change events incorrectly firing?

**Comment by pfrazee** [comment] 2016-10-11 16:43
Anyway, this is moot: we should just compare the hashes.

**Comment by karissa** [comment] 2016-10-18 16:36
@joehand what you said here sounds good: 'The other option would be to do the initial import, set resume: true, then start watching files.'

**Comment by karissa** [comment] 2016-10-18 16:37
@joehand that might be relatd to the dat-js API idea, which is to have a two-step share process:

1) create the keypair
2) start sync

Where sync would be a "resume" action

**Comment by joehand** [comment] 2016-10-18 17:21
> @joehand what you said here sounds good: 'The other option would be to do the initial import, set resume: true, then start watching files.'

We had a bit of discussion on this in [this pr](https://github.com/juliangruber/hyperdrive-import-files/pull/22). 

The issue is that watching after initial import can introduce other bugs, where files are changed in between adding and watching (which could be easy to do for large folders). As Julian said, we should fix the other bugs elsewhere since the watching live after adding files is a non-ideal workaround.

**Comment by karissa** [comment] 2016-11-15 19:32
is it possible to cache the hash in hyperdrive, and then check it against the hash @mafintosh ?

@joehand has a working implementation of checking the read streams but he's worried about performance. He says we need to fix this before we make live watching default

**Comment by joehand** [comment] 2017-02-16 01:01
We fixed this by setting the  `compareFileContent` option to true in hyperdrive-import-files.

**Closed by joehand** 2017-02-16 01:01 UTC
Labels: Type: Bug, v11
